var map_config = {
	'default':{
		'borderColor':'#9CA8B6', //outline color
		'lakesColor':'#31DBF7', // lakes color
		'namesColor':'#919191', //color of short names
		'hoverShadow':'#666666', //tooltip shadow color
	},
	'map_1':{
		'hover': 'ALABAMA', //state hover content
		'url':'http://alabama.'+map_url, //Goto URL
		'target':'new_window', //open link in new window:new_window, open in current window:same_window, or none for nothing.
		'upColor':'transparent', //state's color when page loads
		'overColor':'#FFEE88', //state's color when mouse hover
		'downColor':'#FFEE88',//state's color when mouse clicking
		'enable':true,//true/false to enable/disable this state
	},
	'map_2':{
		'hover': 'ALASKA',
		'url':'http://alaska.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_3':{
		'hover': 'ARIZONA',
		'url':'http://arizona.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_4':{
		'hover': 'ARKANSAS',
		'url':'http://arkansas.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_5':{
		'hover': 'CALIFORNIA',
		'url':'http://california.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_6':{
		'hover': 'COLORADO',
		'url':'http://colorado.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_7':{
		'hover': 'CONNECTICUT',
		'url':'http://connecticut.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_8':{
		'hover': 'DELAWARE',
		'url':'http://delaware.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_9':{
		'hover': 'FLORIDA',
		'url':'http://florida.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_10':{
		'hover': 'GEORGIA',
		'url':'http://georgia.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_11':{
		'hover': 'HAWAII',
		'url':'http://hawaii.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_12':{
		'hover': 'IDAHO',
		'url':'http://idaho.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_13':{
		'hover': 'ILLINOIS',
		'url':'http://illinois.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_14':{
		'hover': 'INDIANA',
		'url':'http://indiana.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_15':{
		'hover': 'IOWA',
		'url':'http://iowa.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_16':{
		'hover': 'KANSAS',
		'url':'http://kansas.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_17':{
		'hover': 'KENTUCKY',
		'url':'http://kentucky.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_18':{
		'hover': 'LOUISIANA',
		'url':'http://louisiana.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_19':{
		'hover': 'MAINE',
		'url':'http://maine.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_20':{
		'hover': 'MARYLAND',
		'url':'http://maryland.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_21':{
		'hover': 'MASSACHUSETTS',
		'url':'http://massachusetts.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_22':{
		'hover': 'MICHIGAN',
		'url':'http://michigan.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_23':{
		'hover': 'MINNESOTA',
		'url':'http://minnesota.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_24':{
		'hover': 'MISSISSIPPI',
		'url':'http://mississippi.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_25':{
		'hover': 'MISSOURI',
		'url':'http://missouri.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_26':{
		'hover': 'MONTANA',
		'url':'http://montana.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_27':{
		'hover': 'NEBRASKA',
		'url':'http://nebraska.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_28':{
		'hover': 'NEVADA',
		'url':'http://nevada.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_29':{
		'hover': 'NEW HAMPSHIRE',
		'url':'http://newhampshire.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_30':{
		'hover': 'NEW JERSEY',
		'url':'http://newjersey.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_31':{
		'hover': 'NEW MEXICO',
		'url':'http://newmexico.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_32':{
		'hover': 'NEW YORK',
		'url':'http://newyork.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_33':{
		'hover': 'NORTH CAROLINA',
		'url':'http://northcarolina.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_34':{
		'hover': 'NORTH DAKOTA',
		'url':'http://northdakota.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_35':{
		'hover': 'OHIO',
		'url':'http://ohio.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_36':{
		'hover': 'OKLAHOMA',
		'url':'http://oklahoma.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_37':{
		'hover': 'OREGON',
		'url':'http://oregon.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_38':{
		'hover': 'PENNSYLVANIA',
		'url':'http://pennsylvania.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_39':{
		'hover': 'RHODE ISLAND',
		'url':'http://rhodeisland.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_40':{
		'hover': 'SOUTH CAROLINA',
		'url':'http://southcarolina.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#FFEE88',
		'enable':true,
	},
	'map_41':{
		'hover': 'SOUTH DAKOTA',
		'url':'http://southdakota.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#FFEE88',
		'enable':true,
	},
	'map_42':{
		'hover': 'TENNESSEE',
		'url':'http://tennessee.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_43':{
		'hover': 'TEXAS',
		'url':'http://texas.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_44':{
		'hover': 'UTAH',
		'url':'http://utah.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_45':{
		'hover': 'VERMONT',
		'url':'http://vermont.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_46':{
		'hover': 'VIRGINIA',
		'url':'http://virginia.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_47':{
		'hover': 'WASHINGTON',
		'url':'http://washington.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_48':{
		'hover': 'WEST VIRGINIA',
		'url':'http://westvirfinia.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_49':{
		'hover': 'WISCONSIN',
		'url':'http://wisconsin.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_50':{
		'hover': 'WYOMING',
		'url':'http://wyoming.'+map_url,
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
}
