var map_config = {
	'default':{
		'borderColor':'#9CA8B6', //outline color
		'lakesColor':'#31DBF7', // lakes color
		'namesColor':'#919191', //color of short names
		'hoverShadow':'#666666', //tooltip shadow color
	},
	'map_1':{
		'hover': 'ALABAMA', //state hover content
		'url':site_url+'state.php?State=AL', //Goto URL
		'target':'new_window', //open link in new window:new_window, open in current window:same_window, or none for nothing.
		'upColor':'transparent', //state's color when page loads
		'overColor':'#FFEE88', //state's color when mouse hover
		'downColor':'#FFEE88',//state's color when mouse clicking
		'enable':true,//true/false to enable/disable this state
	},
	'map_2':{
		'hover': 'ALASKA',
		'url':site_url+'state.php?State=AK',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_3':{
		'hover': 'ARIZONA',
		'url':site_url+'state.php?State=AZ',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_4':{
		'hover': 'ARKANSAS',
		'url':site_url+'state.php?State=AR',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_5':{
		'hover': 'CALIFORNIA',
		'url':site_url+'state.php?State=CA',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_6':{
		'hover': 'COLORADO',
		'url':site_url+'state.php?State=CO',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_7':{
		'hover': 'CONNECTICUT',
		'url':site_url+'state.php?State=CT',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_8':{
		'hover': 'DELAWARE',
		'url':site_url+'state.php?State=DE',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_9':{
		'hover': 'FLORIDA',
		'url':site_url+'state.php?State=FL',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_10':{
		'hover': 'GEORGIA',
		'url':site_url+'state.php?State=GA',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_11':{
		'hover': 'HAWAII',
		'url':site_url+'state.php?State=HI',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_12':{
		'hover': 'IDAHO',
		'url':site_url+'state.php?State=ID',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_13':{
		'hover': 'ILLINOIS',
		'url':site_url+'state.php?State=IL',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_14':{
		'hover': 'INDIANA',
		'url':site_url+'state.php?State=IN',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_15':{
		'hover': 'IOWA',
		'url':site_url+'state.php?State=IA',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_16':{
		'hover': 'KANSAS',
		'url':site_url+'state.php?State=KS',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_17':{
		'hover': 'KENTUCKY',
		'url':site_url+'state.php?State=KY',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_18':{
		'hover': 'LOUISIANA',
		'url':site_url+'state.php?State=LA',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_19':{
		'hover': 'MAINE',
		'url':site_url+'state.php?State=ME',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_20':{
		'hover': 'MARYLAND',
		'url':site_url+'state.php?State=MD',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_21':{
		'hover': 'MASSACHUSETTS',
		'url':site_url+'state.php?State=MA',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_22':{
		'hover': 'MICHIGAN',
		'url':site_url+'state.php?State=MI',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_23':{
		'hover': 'MINNESOTA',
		'url':site_url+'state.php?State=MN',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_24':{
		'hover': 'MISSISSIPPI',
		'url':site_url+'state.php?State=MS',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_25':{
		'hover': 'MISSOURI',
		'url':site_url+'state.php?State=MO',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_26':{
		'hover': 'MONTANA',
		'url':site_url+'state.php?State=MT',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_27':{
		'hover': 'NEBRASKA',
		'url':site_url+'state.php?State=NE',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_28':{
		'hover': 'NEVADA',
		'url':site_url+'state.php?State=NV',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_29':{
		'hover': 'NEW HAMPSHIRE',
		'url':site_url+'state.php?State=NH',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_30':{
		'hover': 'NEW JERSEY',
		'url':site_url+'state.php?State=NJ',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_31':{
		'hover': 'NEW MEXICO',
		'url':site_url+'state.php?State=NM',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_32':{
		'hover': 'NEW YORK',
		'url':site_url+'state.php?State=NY',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_33':{
		'hover': 'NORTH CAROLINA',
		'url':site_url+'state.php?State=NC',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_34':{
		'hover': 'NORTH DAKOTA',
		'url':site_url+'state.php?State=ND',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_35':{
		'hover': 'OHIO',
		'url':site_url+'state.php?State=OH',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_36':{
		'hover': 'OKLAHOMA',
		'url':site_url+'state.php?State=OK',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_37':{
		'hover': 'OREGON',
		'url':site_url+'state.php?State=OR',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_38':{
		'hover': 'PENNSYLVANIA',
		'url':site_url+'state.php?State=PA',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_39':{
		'hover': 'RHODE ISLAND',
		'url':site_url+'state.php?State=RI',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_40':{
		'hover': 'SOUTH CAROLINA',
		'url':site_url+'state.php?State=SC',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#FFEE88',
		'enable':true,
	},
	'map_41':{
		'hover': 'SOUTH DAKOTA',
		'url':site_url+'state.php?State=SD',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#FFEE88',
		'enable':true,
	},
	'map_42':{
		'hover': 'TENNESSEE',
		'url':site_url+'state.php?State=TN',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_43':{
		'hover': 'TEXAS',
		'url':site_url+'state.php?State=TX',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_44':{
		'hover': 'UTAH',
		'url':site_url+'state.php?State=UT',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_45':{
		'hover': 'VERMONT',
		'url':site_url+'state.php?State=VT',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_46':{
		'hover': 'VIRGINIA',
		'url':site_url+'state.php?State=VA',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_47':{
		'hover': 'WASHINGTON',
		'url':site_url+'state.php?State=WA',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_48':{
		'hover': 'WEST VIRGINIA',
		'url':site_url+'state.php?State=WV',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_49':{
		'hover': 'WISCONSIN',
		'url':site_url+'state.php?State=WI',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_50':{
		'hover': 'WYOMING',
		'url':site_url+'state.php?State=WY',
		'target':'new_window',
		'upColor':'transparent',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
}
