<?php

/* space == separator */

$emoticons=array();

$emoticons[]=':) 01.png 01.gif';
$emoticons[]=':( 02.png 02.gif';
$emoticons[]=':D 03.png 03.gif';
$emoticons[]='8-) 04.png 04.gif';
$emoticons[]=':O 05.png 05.gif';
$emoticons[]=';) 06.png 06.gif';
$emoticons[]=';( 07.png 07.gif';
$emoticons[]='(sweat) 08.png 08.gif';
$emoticons[]=':! 09.png 09.gif';
$emoticons[]=':# 10.png 10.gif';
$emoticons[]=':P 11.png 11.gif';
$emoticons[]='(blush) 12.png 12.gif';
$emoticons[]=':~) 13.png 13.gif';
$emoticons[]='!-) 14.png 14.gif';
$emoticons[]='!-( 15.png 15.gif';
$emoticons[]='(inlove) 16.png 16.gif';
$emoticons[]=':]) 17.png 17.gif';
$emoticons[]='(talk) 18.png 18.gif';
$emoticons[]='(yawn) 19.png 19.gif';
$emoticons[]='(puke) 20.png 20.gif';
$emoticons[]='(doh) 21.png 21.gif';
$emoticons[]=':@ 22.png 22.gif';
$emoticons[]='(wasntme) 23.png 23.gif';
$emoticons[]='(party) 24.png 24.gif';
$emoticons[]=':S 25.png 25.gif';
$emoticons[]='(mm) 26.png 26.gif';
$emoticons[]='8-! 27.png 27.gif';
$emoticons[]=':x 28.png 28.gif';
$emoticons[]='(wave) 29.png 29.gif';
$emoticons[]='(call) 30.png 30.gif';
$emoticons[]='(devil) 31.png 31.gif';
$emoticons[]='(angel) 32.png 32.gif';
$emoticons[]='(envy) 33.png 33.gif';
$emoticons[]='(wait) 34.png 34.gif';
$emoticons[]='(hug) 35.png 35.gif';
$emoticons[]='(makeup) 36.png 36.gif';
$emoticons[]='(chuckle) 37.png 37.gif';
$emoticons[]='(clap) 38.png 38.gif';
$emoticons[]='(think) 39.png 39.gif';
$emoticons[]='(bow) 40.png 40.gif';
$emoticons[]='(rofl) 41.png 41.gif';
$emoticons[]='(whew) 42.png 42.gif';
$emoticons[]='(happy) 43.png 43.gif';
$emoticons[]='(smirk) 44.png 44.gif';
$emoticons[]='(nod) 45.png 45.gif';
$emoticons[]='(shake) 46.png 46.gif';
$emoticons[]='(punch) 47.png 47.gif';
$emoticons[]='(emo) 48.png 48.gif';
$emoticons[]='(y) 49.png 49.gif';
$emoticons[]='(n) 50.png 50.gif';
$emoticons[]='(handshake) 51.png 51.gif';
$emoticons[]='(h) 53.png 53.gif';
$emoticons[]='(u) 54.png 54.gif';
$emoticons[]='(e) 55.png 55.gif';
$emoticons[]='(F) 56.png 56.gif';
$emoticons[]='(rain) 57.png 57.gif';
$emoticons[]='(sun) 58.png 58.gif';
$emoticons[]='(o) 59.png 59.gif';
$emoticons[]='(music) 60.png 60.gif';
$emoticons[]='(~~) 61.png 61.gif';
$emoticons[]='(mp) 62.png 62.gif';
$emoticons[]='(coffee) 63.png 63.gif';
$emoticons[]='(pi) 64.png 64.gif';
$emoticons[]='(cash) 65.png 65.gif';
$emoticons[]='(flex) 66.png 66.gif';
$emoticons[]='(~) 67.png 67.gif';
$emoticons[]='(beer) 68.png 68.gif';
$emoticons[]='(d) 69.png 69.gif';
$emoticons[]='(dance) 70.png 70.gif';
$emoticons[]='(ninja) 71.png 71.gif';
$emoticons[]='(#) 72.png 72.gif';

$aliases=array();

?>